### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by blackcow** [ziplab/LITv2#1]
Interesting work !  There are still questions about FLOPs calculation and implementation details.
Is the code gonna be available soon or it s not planned at all?  Thanks : )

**Comment by HubHop** [comment]
Hi @blackcow, thanks for your interest! We are cleaning the code and preparing the pretrained weights. Code will be released later.

**Comment by Yuany966** [comment]
Looking forward to the release of the code

**Comment by yanxinpeng517** [comment]
Looking forward to the release of the code

**Comment by nowander** [comment]
Looking forward to the release of the code

**Comment by bohanzhuang** [comment]
Hi all, 

We have now released the code for reproduction. Feel free to raise any issues, thanks!

Best,
Bohan
