### ISSUE TITLE
Training with non-square images

### ISSUE THREAD

**Issue by ytring** [ziplab/LITv2#10]
Hi, thank you for the great work. 

Can you tell how I can train with non-square images? For example, images with size 640 x 480.

**Comment by HubHop** [comment]
Hi @tonygraf, thanks for your interest! At this moment, most imagenet classfication training scripts are based on squared images. However, it is straightforward to extend the model architecture to handle non-squared images. You can refer to our detection code [here](https://github.com/ziplab/LITv2/blob/main/detection/mmdet/models/backbones/litv2.py) for an example. I will try to find some time to improve the training scripts.

**Comment by ytring** [comment]
Ok. Thank you for your help.
