### ISSUE TITLE
# Build Deformable Convolution cd mm_modules/DCN python setup.py build install

### ISSUE THREAD

**Issue by renqi1998** [ziplab/LITv2#4]
Hello, when I set up a compilation environment for LITv2, I followed your steps and ran python setup.py build install. I encountered an error that there is no cuda, but there is CUDA in the environment. How to solve this?

**Comment by HubHop** [comment]
Hi @renqi1998, it seems like your python environment cannot find the path to CUDA. E.g. CUDA_HOME in your system-level configuration. You can check your CUDA installation by using `nvcc -V` in your terminal. Please make sure you have successfully installed cuda in your operating system.

**Comment by renqi1998** [comment]
Thank you, I used this statement “python3 setup.py install” to compile successfully
