### ISSUE TITLE
large release for the model 

### ISSUE THREAD

**Issue by mathshangw** [ziplab/LITv2#5]
Thanks for sharing the code. I'm interested in your paper but is there any large release for the model?

**Comment by HubHop** [comment]
Hi @mathshangw, thanks for your interest! I assume you refer to a larger model or training on a larger dataset, like Swin-Large and ImageNet-22K. Unfortunately, to train such a  large model on ImageNet-22K is far beyond our existing hardware resources. We will explore this setting in the future.

**Comment by mathshangw** [comment]
appreciate your reply , thanks
