### ISSUE TITLE
关于特征图与窗口大小不能整除的问题

### ISSUE THREAD

**Issue by mjt1312** [ziplab/LITv2#6]
你好，想请教一下在hifi中，H与W不能整除window size ,这种情况怎么办呢？

**Comment by HubHop** [comment]
你好，这种情况下HiLo的做法是对feature map做padding，可以参考HiLo在object detection上的方案：https://github.com/ziplab/LITv2/blob/main/detection/mmdet/models/backbones/litv2.py#L216

**Comment by mjt1312** [comment]
superhero
***@***.***

好的好的，特别感谢您的回复！！！！

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ziplab/LITv2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ziplab/LITv2] 关于特征图与窗口大小不能整除的问题 (Issue #6)





 
你好，这种情况下HiLo的做法是对feature map做padding，可以参考HiLo在object detection上的方案：https://github.com/ziplab/LITv2/blob/main/detection/mmdet/models/backbones/litv2.py#L216
