### ISSUE TITLE
Frequency magnitude visualization

### ISSUE THREAD

**Issue by Yanll2021** [ziplab/LITv2#7]
We would like to learn the technology of frequency magnitude visualization in your paper. Could you share the relevant code? Thank you very much.

My email address is 18813178137@163.com

![image](https://user-images.githubusercontent.com/78201260/204016595-5fea855c-2e9b-4270-8cc7-a34013f4fd3e.png)

**Comment by HubHop** [comment]
Hi @Yanll2021, thanks for your interest! Please refer to [here ](https://github.com/ziplab/LITv2/issues/3)for the visualization code.
